# Generated by Django 3.2.9 on 2021-11-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='dmo_codigo', max_length=1, unique=True, verbose_name='código MO')),
                ('descripcion', models.CharField(db_column='dmo_descrip', max_length=100, verbose_name='descripción')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='descuento MO')),
            ],
            options={
                'verbose_name': 'Descuento MO',
                'verbose_name_plural': 'Descuentos MO',
                'db_table': 'sirtbdmo',
            },
        ),
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='fpg_codigo', max_length=2, unique=True, verbose_name='código')),
                ('descripcion', models.CharField(db_column='fpg_descrip', max_length=100, verbose_name='descripción')),
                ('recibos', models.IntegerField(db_column='fpg_recibos', default=0, verbose_name='recibos')),
                ('diasvto', models.IntegerField(db_column='fpg_diasvto', default=0, verbose_name='días vencimiento factura')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'sirtbfpg',
            },
        ),
        migrations.CreateModel(
            name='TipoClienteRecambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='tcr_codigo', max_length=2, unique=True, verbose_name='código')),
                ('descripcion', models.CharField(db_column='tcr_descrip', max_length=100, verbose_name='descripción')),
                ('datocon', models.CharField(db_column='tcr_datocon', max_length=1, verbose_name='datocon')),
            ],
            options={
                'verbose_name': 'Tipo de Cliente Recambios',
                'verbose_name_plural': 'Tipos de Cliente Recambios',
                'db_table': 'sirtbtcr',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='ban_codcsp', max_length=4, verbose_name='código banco')),
                ('sucursal', models.CharField(db_column='ban_sucursal', max_length=4, verbose_name='sucursal')),
                ('cuenta', models.CharField(db_column='ban_cuenta', max_length=15, null=True, verbose_name='número cuenta')),
                ('dgc', models.CharField(db_column='ban_dgc', max_length=1, null=True, verbose_name='dígito control')),
                ('dgc2', models.CharField(db_column='ban_dgc2', max_length=1, null=True, verbose_name='dígito control 2')),
                ('codbcoe', models.CharField(db_column='ban_codbcoe', max_length=8, null=True)),
                ('razonsocial', models.CharField(db_column='ban_rsocial', max_length=100, null=True, verbose_name='razón social')),
                ('tipovia', models.CharField(db_column='ban_tipovia', max_length=2, null=True, verbose_name='tipo vía')),
                ('nomvia', models.CharField(db_column='ban_nomvia', max_length=100, null=True, verbose_name='nombre vía')),
                ('numvia', models.CharField(db_column='ban_numvia', max_length=3, null=True, verbose_name='número vía')),
                ('codpostal', models.CharField(db_column='ban_cpostal', max_length=5, null=True, verbose_name='código postal')),
                ('municipio', models.CharField(db_column='ban_mncipio', max_length=100, null=True, verbose_name='municipio')),
                ('provincia', models.CharField(db_column='ban_provin', max_length=100, null=True, verbose_name='provincia')),
                ('telex', models.CharField(db_column='ban_telex', max_length=25, null=True, verbose_name='telex')),
                ('prefijo', models.IntegerField(db_column='ban_preftel', null=True, verbose_name='prefijo teléfono')),
                ('telefono', models.IntegerField(db_column='ban_telef', null=True, verbose_name='teléfono')),
                ('telperso', models.IntegerField(db_column='ban_telper', null=True, verbose_name='teléfono personal')),
                ('extension', models.IntegerField(db_column='ban_extelf', null=True, verbose_name='extensión')),
                ('contacto', models.CharField(db_column='ban_contac', max_length=100, null=True, verbose_name='contacto')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'sirtbban',
                'unique_together': {('codigo', 'sucursal')},
            },
        ),
    ]
